##########################################################################################
#                                 Dataset object list
##########################################################################################
# mvtec dataset object list
mvtec_obj_list = [
    "bottle",
    "cable",
    "capsule",
    "carpet",
    "grid",
    "hazelnut",
    "leather",
    "metal nut",
    "pill",
    "screw",
    "tile",
    "toothbrush",
    "transistor",
    "wood",
    "zipper",
]
# visa dataset object list
visa_obj_list = [
    "candle",
    "cashew",
    "chewinggum",
    "fryum",
    "pipe fryum",
    "macaroni1",
    "macaroni2",
    "pcb1",
    "pcb2",
    "pcb3",
    "pcb4",
    "capsules",
]
# mpdd dataset object list
mpdd_obj_list = ['bracket black', 'bracket brown', 'bracket white', 'connector', 'metal plate', 'tubes']
# btad dataset object list
btad_object_list = ['01', '02', '03']
# DAGM_KaggleUpload dataset object list
DAGM_KaggleUpload_obj_list = ['Class1', 'Class2', 'Class3', 'Class4', 'Class5', 'Class6', 'Class7', 'Class8', 'Class9', 'Class10']
# SDD dataset object_list
SDD_obj_list = ['SDD']
# DTD dataset object list
DTD_obj_list = ['Woven 001', 'Woven 127', 'Woven 104', 'Stratified 154', 'Blotchy 099', 'Woven 068', 'Woven 125', 'Marbled 078', 'Perforated 037', 'Mesh 114', 'Fibrous 183', 'Matted 069']
# colon dataset object list
colon_obj_list = ['colon']
# ISBI dataset object list
ISBI_obj_list = ['skin']
# Chest dataset object list
Chest_obj_list = ['chest']
# thyroid dataset object list
thyroid_obj_list = ['thyroid']


object_list = {
    'visa': visa_obj_list,
    'mvtec': mvtec_obj_list,
    'mpdd': mpdd_obj_list,
    'btad': btad_object_list,
    'dagm': DAGM_KaggleUpload_obj_list,
    'sdd': SDD_obj_list,
    'dtd': DTD_obj_list,
    'colon': colon_obj_list,
    'ISBI': ISBI_obj_list,
    'chest': Chest_obj_list,
    'thyroid': thyroid_obj_list,
}


##########################################################################################
#                             Anomaly details generated by gpt
##########################################################################################
# mvtec dataset anomaly details generated by gpt
mvtec_anomaly_detail_gpt = {
    "carpet": "discoloration in a specific area,irregular patch or section with a different texture,frayed edges or unraveling fibers,burn mark or scorching",
    "grid": "crooked,cracks,excessive gaps,discoloration,deformation,missing,inconsistent spacing between grid elements,corrosion,visible signs,chipping",
    "leather": "scratches,discoloration,creases,uneven texture,tears,brittleness,damage,seams,heat damage,mold",
    "tile": "chipped,irregularities,discoloration,efflorescence,warping,missing,depressions,lippage,fungus,damage",
    "wood": "knots,warping,cracks along the grain,mold growth on the surface,staining from water damage,wood rot,woodworm holes,rough patches,protruding knots",
    "bottle": "cracked large,cracked small,dented large,dented small,leaking,discolored,deformed,missing cap,excessive condensation,unusual odor",
    "cable": "twisted,knotted cable strands,detached connectors,excessive stretching,dents,corrosion,scorching along the cable,exposed conductive material",
    "capsule": "irregular shape,discoloration coloring,crinkled,uneven seam,condensation inside the capsule,foreign particles,unusually soft or hard",
    "hazelnut": "fungal growth,Unusual discoloration,rotten or foul odor emanating,insect infestation,wetness,misshapen shell,unusually thin,contaminants,unusual texture",
    "metal nut": "cracks,irregular threading,corrosion,missing,distortion,signs of discoloration,excessive wear on contact surfaces,inconsistent texture",
    "pill": "irregular shape,crumbling texture,excessive powder,Uneven coating,presence of air bubbles,disintegration,abnormal specks",
    "screw": "rust on the surface,bent,damaged threads,stripped threads,deformed top,coating damage,uneven grooves,inconsistent size",
    "toothbrush": "loose bristles,uneven bristle distribution,excessive shedding of bristles,staining on the bristles,abrasive texture,irregularities in the shape",
    "transistor": "burn marks,detached leads,signs of corrosion,irregularities in the shape,presence of cracks or fractures,signs of physical trauma,irregularities in the surface texture",
    "zipper": "bent,frayed,misaligned,excessive stiffness,corroded,detaches,loose,warped",
}

# visa dataset anomaly details generated by gpt
visa_anomaly_detail_gpt = {
    "candle": "cracks or fissures in the wax,Wax pooling unevenly around the wick,tunneling,incomplete wax melt pool,irregular or flickering flame,other,extra wax in candle,wax melded out of the candle",
    "capsules": "uneven capsule size,capsule shell appears brittle,excessively soft,dents,condensation,irregular seams or joints,specks",
    "cashew": "uneven coloring,fungal growth,presence of foreign objects,unusual texture,empty shells,signs of moisture,stuck together",
    "chewinggum": "consistency,presence of foreign objects,uneven coloring,excessive hardness,similar colour spot",
    "fryum": "irregular shape,unusual odor,uneven coloring,unusual texture,small scratches,different colour spot,fryum stuck together,other",
    "macaroni1": "uneven shape ,small scratches,small cracks,uneven coloring,signs of insect infestation,uneven texture,Unusual consistency",
    "macaroni2": "irregular shape,small scratches,presence of foreign particles,excessive moisture,Signs of infestation,small cracks,unusual texture",
    "pcb1": "oxidation on the copper traces,separation of layers,presence of solder bridges,excessive solder residue,discoloration,Uneven solder joints,bowing of the board,missing vias",
    "pcb2": "oxidation on the copper traces,separation of layers,presence of solder bridges,excessive solder residue,discoloration,Uneven solder joints,bowing of the board,missing vias",
    "pcb3": "oxidation on the copper traces,separation of layers,presence of solder bridges,excessive solder residue,discoloration,Uneven solder joints,bowing of the board,missing vias",
    "pcb4": "oxidation on the copper traces,separation of layers,presence of solder bridges,excessive solder residue,discoloration,Uneven solder joints,bowing of the board,missing vias",
    "pipe fryum": "uneven shape,presence of foreign objects,different colour spot,unusual odor,empty interior,unusual texture,similar colour spot,stuck together",
}

mpdd_anomaly_detail_gpt ={
  "bracket black": "hole, scratches, uneven surface, chipped edge, peeling paint, inconsistent color, stains, cracks, minor rust, bent",
  "bracket brown": "bent, parts mismatch, uneven surface, chipped edge, peeling paint, inconsistent color, stains, cracks, minor rust, scratches, deformed",
  "bracket white": "defective painting, scratches, uneven surface, chipped edge, peeling paint, inconsistent color, stains, cracks, minor rust, missing parts, deformed",
  "connector": "parts mismatch, loose connection, poor soldering, oxidized surface, scratches, deformed, missing parts, poor contact, loose",
  "metal plate": "major rust, total rust, scratches, uneven surface, chipped edge, peeling paint, severe rust, cracks, holes, deformed, corrosion",
  "tubes": "anomalous, internal blockage, deformed, abnormal bending, uneven surface, chipped edge, peeling paint, severe rust, cracks, holes, internal damage, external damage"
}

dtd_anomaly_detail_gpt = {
  "Woven 001": "loose or broken threads, uneven texture, color inconsistencies, loose threads or fraying, visible knots or tangles, distorted pattern, ragged or damaged edges",
  "Woven 127": "loose or broken threads, uneven texture, color inconsistencies, loose threads or fraying, visible knots or tangles, distorted pattern, ragged or damaged edges",
  "Woven 104": "loose or broken threads, uneven texture, color inconsistencies, loose threads or fraying, visible knots or tangles, distorted pattern, ragged or damaged edges",
  "Stratified 154": "blurred or indistinct layer boundaries, uneven surface, color inconsistencies within layers, cracks or gaps between layers, variable thickness, misaligned layers, ragged or damaged edges",
  "Blotchy 099": "indistinct or blurred blotches, uneven background, color inconsistencies in blotches, bleeding or smudging, uneven distribution of blotches, ragged or damaged edges",
  "Woven 068": "loose or broken threads, uneven texture, color inconsistencies, loose threads or fraying, visible knots or tangles, distorted pattern, ragged or damaged edges",
  "Woven 125": "loose or broken threads, uneven texture, color inconsistencies, loose threads or fraying, visible knots or tangles, distorted pattern, ragged or damaged edges",
  "Marbled 078": "indistinct or blurred marble patterns, uneven background, color inconsistencies in transitions, bleeding or smudging, uneven distribution of patterns, ragged or damaged edges",
  "Perforated 037": "irregularly spaced holes, uneven surface around holes, inconsistent hole size, jagged or rough edges around holes, ragged or damaged edges, missing or extra holes",
  "Mesh 114": "irregular or inconsistent mesh pattern, uneven texture, inconsistent opening size, loose or broken threads, visible knots or tangles, ragged or damaged edges",
  "Fibrous 183": "coarse or unevenly distributed fibers, uneven texture, color inconsistencies, clumping or matting, ragged or damaged edges",
  "Matted 069": "loosely packed fibers, uneven surface, color inconsistencies, loose fibers, ragged or damaged edges"
}

sdd_anomaly_detail_gpt = {
  "SDD": "surface scratches or grooves, color inconsistencies or discoloration, worn or rounded segment edges, visible wear or damage on segments, misalignment with the motor shaft, presence of debris or contaminants, poor electrical conductivity, visible corrosion or oxidation, loose or missing components, uneven brush wear or damaged brushes, inconsistent gap between segments, rough rotation with vibration or noise, arcing or sparking during operation, overheating"
}

btad_anomaly_detail_gpt = {
  "01": "visible scratches or grooves, deformations or irregularities, color inconsistencies or discoloration",
  "02": "cracks or splits in the wood, discoloration or stains, irregular grain patterns",
  "03": "blurred or indistinct layer boundaries, cracks or deformations within layers, color inconsistencies or discoloration"
}

dagm_anomaly_detail_gpt = {
  "Class1": "scratches, stains, cracks affecting the woven texture",
  "Class2": "fiber breaks, fiber tangling, stains affecting the fibrous texture",
  "Class3": "color inconsistencies, particle clustering, holes affecting the granular texture",
  "Class4": "line breaks, uneven lines, blurred center point affecting the radiating lines",
  "Class5": "color inconsistencies, particle clustering, holes affecting the granular texture",
  "Class6": "color inconsistencies, particle clustering, holes affecting the granular texture",
  "Class7": "line breaks, uneven lines, blurred lines affecting the vertical lines",
  "Class8": "stripe breaks, uneven stripes, blurred stripes affecting the vertical stripes",
  "Class9": "color inconsistencies, particle clustering, holes affecting the granular texture",
  "Class10": "line breaks, uneven lines, blurred lines affecting the radiating lines"
}

anomaly_detail_gpt = {
    'visa': visa_anomaly_detail_gpt,
    'mvtec': mvtec_anomaly_detail_gpt,
    'mpdd': mpdd_anomaly_detail_gpt,
    'dtd': dtd_anomaly_detail_gpt,
    'sdd': sdd_anomaly_detail_gpt,
    'btad': btad_anomaly_detail_gpt,
    'dagm': dagm_anomaly_detail_gpt,
}
##########################################################################################
#                             Anomaly details generated by gpt
##########################################################################################
visa_normal_detail_gpt = {
    "candle": "smooth surface, no cracks or fissures, wax evenly distributed around the wick, flat and circular melt pool, no tunneling, wick upright and centered, no excess wax or spillage, uniform color with no spots or color variation",
    "capsules": "uniform capsule size, smooth capsule shell, no brittleness, no excessive softness, no dents, no condensation, regular seams or joints, no specks",
    "cashew": "uniform color, no fungal growth, no foreign objects, normal texture, full shells, no signs of moisture, not stuck together",
    "chewinggum": "uniform color, no foreign objects, smooth surface, no color spots, consistent hardness",
    "fryum": "regular shape, no unusual odor, uniform color, smooth surface, no small scratches, no color spots, not stuck together",
    "macaroni1": "regular shape, no small scratches, no small cracks, uniform color, no signs of insect infestation, smooth texture, consistent consistency",
    "macaroni2": "regular shape, no small scratches, no foreign particles, no excessive moisture, no signs of infestation, no small cracks, smooth texture",
    "pcb1": "no oxidation on the copper traces, no separation of layers, no solder bridges, no excessive solder residue, uniform color, even solder joints, no bowing of the board, all vias present",
    "pcb2": "no oxidation on the copper traces, no separation of layers, no solder bridges, no excessive solder residue, uniform color, even solder joints, no bowing of the board, all vias present",
    "pcb3": "no oxidation on the copper traces, no separation of layers, no solder bridges, no excessive solder residue, uniform color, even solder joints, no bowing of the board, all vias present",
    "pcb4": "no oxidation on the copper traces, no separation of layers, no solder bridges, no excessive solder residue, uniform color, even solder joints, no bowing of the board, all vias present",
    "pipe fryum": "regular shape, no foreign objects, uniform color, no color spots, no unusual odor, empty interior, smooth texture, not stuck together"
}
mvtec_normal_detail_gpt = {
    "carpet": "smooth surface, no wrinkles or bubbles, uniform pattern, no missing or misaligned parts, uniform color with no spots or color variation, no foreign objects or stains",
    "grid": "clear grid lines, no breaks or missing sections, uniform grid spacing, no twists or deformations, uniform color with no spots or color variation, no foreign objects or stains",
    "leather": "smooth surface, no scratches or cracks, uniform color with no spots or color variation, no foreign objects or stains, consistent texture with no abnormal bumps or depressions",
    "tile": "smooth surface, no cracks or fractures, clear pattern, no missing or misaligned parts, uniform color with no spots or color variation, no foreign objects or stains",
    "wood": "smooth surface, no cracks or fractures, clear grain, no missing or misaligned parts, uniform color with no spots or color variation, no foreign objects or stains",
    "bottle": "transparent body, no cracks or fractures, complete label, no missing or misaligned parts, uniform color with no spots or color variation, clean surface with no foreign objects or stains",
    "cable": "smooth surface, no scratches or cracks, uniform color with no spots or color variation, no foreign objects or stains, intact connectors with no looseness or damage",
    "capsule": "uniform size, smooth capsule shell, no brittleness, no excessive softness, no dents, no condensation, regular seams or joints, no specks, uniform color with no spots or color variation",
    "hazelnut": "uniform color, no fungal growth, no foreign objects, normal texture, full shells, no signs of moisture, not stuck together",
    "metal nut": "smooth surface, no scratches or rust, clear threads, no missing or damaged parts, uniform color with no spots or color variation, regular shape with no deformation or twisting, no foreign objects or stains",
    "pill": "smooth surface, no scratches or cracks, uniform color with no spots or color variation, regular shape with no deformation or missing corners, no foreign objects or stains, complete packaging with no damage or openings",
    "screw": "smooth surface, no scratches or rust, clear threads, no missing or damaged parts, uniform color with no spots or color variation, regular shape with no deformation or twisting, no foreign objects or stains",
    "toothbrush": "neat bristles, no shedding or damage, smooth handle surface, no scratches or cracks, uniform color with no spots or color variation, regular shape with no deformation or twisting, no foreign objects or stains",
    "transistor": "smooth surface, no scratches or cracks, aligned pins, no bent or missing parts, uniform color with no spots or color variation, regular shape with no deformation or twisting, no foreign objects or stains",
    "zipper": "smooth operation, no jamming or damage, aligned teeth, no missing or misaligned parts, uniform color with no spots or color variation, smooth surface with no scratches or cracks, no foreign objects or stains"
}

mpdd_normal_detail_gpt = {
  "bracket black": "smooth surface, clean edges, even paint finish, consistent color, free of stains, straight and rigid, well-aligned components, properly assembled",
  "bracket brown": "smooth surface, clean edges, even paint finish, consistent color, free of stains, straight and rigid, well-aligned components, properly assembled, robust structure",
  "bracket white": "smooth surface, clean edges, even paint finish, consistent color, free of stains, straight and rigid, well-aligned components, properly assembled, bright and clean",
  "connector": "secure connection, properly soldered, clean and shiny surface, smooth edges, well-aligned components, properly assembled, functional and reliable",
  "metal plate": "smooth surface, clean edges, even paint finish, consistent color, free of stains, straight and flat, well-aligned components, properly assembled, corrosion-resistant",
  "tubes": "smooth surface, clean edges, even paint finish, consistent color, free of stains, straight and uniform, well-aligned components, properly assembled, unobstructed interior, durable and strong"
}
dtd_normal_detail_gpt = {
  "Woven 001": "tightly woven threads, smooth and even texture, consistent color throughout, free of loose threads, no visible knots or tangles, well-defined pattern, clean and neat edges",
  "Woven 127": "tightly woven threads, smooth and even texture, consistent color throughout, free of loose threads, no visible knots or tangles, well-defined pattern, clean and neat edges",
  "Woven 104": "tightly woven threads, smooth and even texture, consistent color throughout, free of loose threads, no visible knots or tangles, well-defined pattern, clean and neat edges",
  "Stratified 154": "clear layering with distinct boundaries, smooth and even surface, consistent color within each layer, no cracks or gaps between layers, uniform thickness, well-aligned layers, clean and neat edges",
  "Blotchy 099": "distinct and well-defined blotches, smooth and even background, consistent color in blotches, no bleeding or smudging, even distribution of blotches, clean and neat edges",
  "Woven 068": "tightly woven threads, smooth and even texture, consistent color throughout, free of loose threads, no visible knots or tangles, well-defined pattern, clean and neat edges",
  "Woven 125": "tightly woven threads, smooth and even texture, consistent color throughout, free of loose threads, no visible knots or tangles, well-defined pattern, clean and neat edges",
  "Marbled 078": "distinct and well-defined marble patterns, smooth and even background, consistent color transitions, no bleeding or smudging, even distribution of patterns, clean and neat edges",
  "Perforated 037": "uniformly spaced holes, smooth and even surface around holes, consistent hole size, no jagged or rough edges around holes, clean and neat edges, no missing or extra holes",
  "Mesh 114": "uniform and consistent mesh pattern, smooth and even texture, consistent opening size, no loose or broken threads, no visible knots or tangles, clean and neat edges",
  "Fibrous 183": "fine and evenly distributed fibers, smooth and even texture, consistent color throughout, no clumping or matting, clean and neat edges",
  "Matted 069": "densely packed fibers, smooth and even surface, consistent color throughout, no loose fibers, clean and neat edges"
}
sdd_normal_detail_gpt = {
  "SDD": "smooth and clean surface, even and consistent color, well-defined segments with sharp edges, no visible wear or damage, properly aligned with the motor shaft, free of debris or contaminants, good electrical conductivity, no visible corrosion or oxidation, securely fastened components, properly functioning brushes with even wear, consistent gap between segments, smooth rotation without vibration or noise"
}

btad_normal_detail_gpt = {
  "01": "smooth and uniform surface, no visible scratches or deformations, consistent color and texture",
  "02": "clear and consistent grain pattern, uniform color and texture, no visible cracks or defects",
  "03": "clear and distinct layer boundaries, uniform color and texture across layers, no visible cracks or deformations"
}

dagm_normal_detail_gpt = {
  "Class1": "uniform, regular woven texture with smooth surface and no visible defects",
  "Class2": "uniform, dense fibrous texture with smooth surface and no visible defects",
  "Class3": "uniform, dense granular texture with smooth surface and no visible defects",
  "Class4": "uniform, symmetrical radiating lines with clear distribution and no visible defects",
  "Class5": "uniform, dense granular texture with smooth surface and no visible defects",
  "Class6": "uniform, dense granular texture with smooth surface and no visible defects",
  "Class7": "uniform, dense vertical lines with clear distribution and no visible defects",
  "Class8": "uniform, dense vertical stripes with clear distribution and no visible defects",
  "Class9": "uniform, dense granular texture with smooth surface and no visible defects",
  "Class10": "uniform, clear radiating lines with clear distribution and no visible defects"
}

normal_detail_gpt = {
    'visa': visa_normal_detail_gpt,
    'mvtec': mvtec_normal_detail_gpt,
    'mpdd': mpdd_normal_detail_gpt,
    'dtd': dtd_normal_detail_gpt,
    'sdd': sdd_normal_detail_gpt,
    'btad': btad_normal_detail_gpt,
    'dagm': dagm_normal_detail_gpt,
}

##########################################################################################
#                                normal or abnormal status
##########################################################################################
# normal status
status_normal = [
    "{}",
    "flawless {}",
    "perfect {}",
    "unblemished {}",
    "{} without flaw",
    "{} without defect",
    "{} without damage",
]
# abnormal status
status_abnormal_winclip = [
    "damaged {}",
    "broken {}",
    "{} with flaw",
    "{} with defect",
    "{} with damage",
]

import re
def gen_prompt_status(dataset_list:list =['visa', 'mvtec', 'mpdd', 'dtd', 'sdd', 'btad', 'dagm'], is_only_abnormal=False):
    prompt_normal, prompt_abnormal = {}, {}
    cls_map = {}
    for dataset_type in dataset_list:
        if dataset_type == 'btad':
            cls_map.update({"01":"ring components", "02": "wood materials", "03": "layered components"})
            continue
        if dataset_type == 'dagm':
            cls_map.update({"Class1": "texture", "Class2": "texture", "Class3": "texture",
                            "Class4": "texture", "Class5": "texture", "Class6": "texture",
                            "Class7": "texture", "Class8": "texture", "Class9": "texture",
                            "Class10": "texture"})
            continue
        if dataset_type == 'sdd':
            cls_map.update({"SDD":"electrical commutators"})
            continue
        oringal_class_names = object_list[dataset_type]
        dataset_cls_map = {cls_name: re.sub(r'[\d_]+', '', cls_name) for cls_name in oringal_class_names}  # pcb1 -> pcb
        cls_map.update(dataset_cls_map)

    for dataset_type in dataset_list:
        oringal_class_names = object_list[dataset_type]
        anomaly_detail_gpt_dataset = anomaly_detail_gpt[dataset_type]
        normal_detail_gpt_dataset = normal_detail_gpt[dataset_type]
        for class_name in oringal_class_names:
            prompt_abnormal[class_name] = ['abnormal {} ' + 'with {}'.format(x)
                                           for x in anomaly_detail_gpt_dataset[class_name].split(',')] \
                                           + status_abnormal_winclip
            if is_only_abnormal:
                prompt_normal[class_name] = status_normal
            else:
                prompt_normal[class_name] = ['normal {} ' + 'with {}'.format(x)
                                             for x in normal_detail_gpt_dataset[class_name].split(',')] \
                                            + status_normal


    return prompt_normal, prompt_abnormal, cls_map



if __name__ == '__main__':
    prompt_normal, prompt_abnormal, cls_map = gen_prompt_status()
    print(cls_map)